// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using TitanicWeather.Models;

#nullable disable

namespace TitanicWeather.TitanicContext
{
    public partial class TitanicdatabaseContext : DbContext
    {
        public TitanicdatabaseContext()
        {
        }

        public TitanicdatabaseContext(DbContextOptions<TitanicdatabaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Measurement> Measurements { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=titanicserver.database.windows.net;Initial Catalog=TitanicDatabase;Persist Security Info=True;User ID=titanicAdmin;Password=Drowning123");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Measurement>(entity =>
            {
                entity.Property(e => e.DateAndTime).HasColumnType("datetime");

                entity.Property(e => e.Humidity).HasColumnType("decimal(10, 4)");

                entity.Property(e => e.Pressure).HasColumnType("decimal(10, 4)");

                entity.Property(e => e.Temperature).HasColumnType("decimal(10, 4)");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}